# Generated by Django 6.0.3 on 2026-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
