# Generated by Django 6.0.3 on 2026-04-07 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0002_alter_save_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='save',
            name='activityTemplates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='save',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='save',
            name='name',
            field=models.CharField(default='Новое сохранение', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 7, 14, 12, 5, 376064, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
