# Generated by Django 6.0.3 on 2026-04-07 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0003_save_activities_save_activitytemplates_save_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
