# Generated by Django 6.0.3 on 2026-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0004_alter_save_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='save',
            name='activityTemplates',
        ),
        migrations.RemoveField(
            model_name='save',
            name='end',
        ),
        migrations.RemoveField(
            model_name='save',
            name='name',
        ),
        migrations.RemoveField(
            model_name='save',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='save',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
