# Generated by Django 6.0.3 on 2026-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0005_remove_save_activities_remove_save_activitytemplates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={},
        ),
        migrations.RenameField(
            model_name='save',
            old_name='save_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='save',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='save',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
