# Generated by Django 6.0.3 on 2026-04-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0006_alter_save_options_rename_save_file_save_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='updated_at',
        ),
    ]
