# Generated by Django 6.0.3 on 2026-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0007_remove_save_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='tag',
            field=models.FileField(blank=True, max_length=36, upload_to=''),
        ),
    ]
