# Generated by Django 6.0.3 on 2026-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0008_save_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='tag',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
