# Generated by Django 6.0.3 on 2026-04-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0009_alter_save_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='tag',
            new_name='name',
        ),
    ]
